export const SEARCH_DATA_START = "SEARCH_DATA_START";
export const SEARCH_DATA_SUCCESS = "SEARCH_DATA_SUCCESS";
export const SEARCH_DATA_ERROR = "SEARCH_DATA_ERROR";

export const TOGGLE_BLUR = "TOOGLE_BLUR";
export const HANDLE_INPUT = "HANDLE_INPUT";
export const TOGGLE_BURGER_MENU = "TOGGLE_BURGER_MENU";
export const MAKE_WINDOW_STIKY = "MAKE_WINDOW_STIKY";
